version: '3.8'

services:
# Product Service
  product-service:
    build: .
    container_name: product-service
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../ProductService:/var/www
      - ../ProductService/storage/logs:/var/www/storage/logs
    networks:
      - microservices-network
    depends_on:
      - product-db


  product-db:
    image: mysql:8.0
    container_name: product_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: product
      MYSQL_ROOT_PASSWORD: productroot
      MYSQL_PASSWORD: productpass
      MYSQL_USER: productuser
    volumes:
      - productdbdata:/var/lib/mysql
    ports:
      - "3302:3306"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx-product:
    image: nginx:1.19-alpine
    container_name: nginx-product
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ../ProductService:/var/www
      - ./nginx/product.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservices-network
    depends_on:
      - product-service


networks:
  microservices-network:
     external: true

volumes:
  productdbdata: